#!/bin/bash -eu

# ****************************************************************************
# DESCRIPTION
#
# Create docker volume by local path content
#
# bugs and hints: lrsklemstein@gmail.com
# ****************************************************************************


# --- constants

readonly PROG=${0##*/}

readonly IMAGE=alpine


# --- functions

print_usage_and_exit() {
    echo "$PROG LOCAL_PATH volume_name" >&2
    exit 2
}

msg() {
    echo "[$PROG] $*"
}

abort() {
    msg "$*"
    exit 1
}

docker_volume_exists() {
    local volume_name="$1"

    docker volume ls --quiet | grep -q "$volume_name"
}


# --- main

[ $# -eq 2 ] || print_usage_and_exit

local_path="$(readlink -f $1)"
volume_name="$2"

[ -d "$local_path" ] || \
    abort "local path \"$local_path\" not found"

docker_volume_exists "$volume_name" && \
    abort "volume name \"$volume_name\" already exists."

docker volume create "$volume_name" 
msg "Created volume \"$volume_name\""

docker run -it --rm \
    -v ${local_path}:/mnt:ro \
    -v ${volume_name}:/mnt_vol \
    ${IMAGE:-alpine} \
    /bin/sh -c "/bin/cp -r /mnt/* /mnt_vol"

msg "Populated new volume \"$volume_name\" with content from \"$local_path\"."
exit 0
