#!/bin/bash -eu

# fmove = find and move

# replacement for the common pattern
#
# find DIR -type f -name pattern -exec mv {} DEST \;

readonly PROGNAME="${0##*/}"

readonly MV=/usr/bin/mv
readonly MKDIR=/usr/bin/mkdir

if [ $# -lt 3 ]
then
    echo "usage: $PROGNAME DIR pattern DEST [find opts]" >&2
    exit 2
fi

dir="$1"
pattern="$2"
dest="$3"
shift 3
find_opts=${*:-}

[ -d "$dest" ] || $MKDIR -p "$dest"

find "$dir" $find_opts -type f -name "$pattern" -exec $MV -v '{}' "$dest" ';'

echo "$PROGNAME: Done." >&2
