#!/bin/bash -eu

# mkpep = make pipenv project (with pyenv in mind)

# bugs and hints: lrsklemstein@gmail.com


export PIPENV_VENV_IN_PROJECT=1


msg() {
    echo "$*" >&2
}

abort() {
    msg "$*"
    exit 1
}

main() {
    [ $# -eq 1 -o $# -eq 2 ] || print_usage_and_exit

    project_dir="$1"
    py_version="${2:-}"

    if [ -d "$project_dir" ]
    then
        abort "project dir \"$project_dir\" already exists"
    fi

    if [ -z "$py_version" ]
    then
        py_version=$(get_major_py_version)
    fi

    mkdir -p "$project_dir"
    cd "$project_dir"

    pipenv --python $py_version

    exit 0
}

print_usage_and_exit() {
    progname=${0##*/}
    msg "usage: $progname PROJECT_DIR [python_version]"
    exit 2
}

get_major_py_version() {
    if which pyenv >/dev/null 2>&1
    then
        pv=$(pyenv versions | grep -v '^\* *system' |tr -d ' ' |tail -1)
    else
        pv=$(which python3)
    fi

    cut -d. -f1,2 <<< $pv
}


main "$@"
