#!/bin/bash -eu

# ****************************************************************************
#  DESCRIPTION
#    Create a local git repo dir and take care about the master vs. main
#    trouble.
#
# bugs and hints: lrsklemstein@gmail.com
# ****************************************************************************

readonly PROG=${0##*/}


if [ $# -ne 1 ]
then
    echo "usage: $PROG GIT_DIR" 1>&2
    exit 2
fi

msg() {
    echo "[$PROG] $*" 1>&2
}

abort() {
    msg "$*"
    exit 1
}

git_dir="$1"

[ -d "$git_dir" ] &&  abort "dir \"$git_dir\" already exist"

mkdir -p "$git_dir"

cd "$git_dir"

git init

branch=$(git status | awk '/^On branch/ {print $3}')

if [ "$branch" != "main" ]
then
    git branch -m "$branch" main
    msg "Changed branch to \"main\""
fi

msg "Done."
