#!/bin/bash -eu

# ****************************************************************************
# DESCRIPTION
#
# Create a local python project using pyenv and pipenv with an initial python
# program in it + shell wrapper.
# ****************************************************************************

# bugs and hints: lrsklemstein@gmail.com
#

# --- constants

PROG=${0##*/}

# --- functions

print_usage_and_exit() {
    echo "Usage: $PROG dirname [pyversion]" >&2
    exit 2
}

msg() {
    {
        echo ""
        echo "[$PROG] $*"
        echo ""
    } >&2
}


# --- main

[ $# -eq 1 -o $# -eq 2 ] || print_usage_and_exit

dirname="$1"

if [ $# -eq 2 ]
then
    pyversion="$2"
else
    pyversion=$(pyenv versions | tr -d ' ' \
        | egrep '^[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
fi

msg "Python version == $pyversion"

if [ -d "$dirname" ]
then
    echo "directory $dirname already exists" >&2
    exit 1
fi

mkdir -p "$dirname"
cd $dirname

msg "Now in ${dirname}..."


msg "Set pyenv version..."
pyenv local $pyversion


msg "Run pipenv install..."
pipenv install --python $pyversion

progname=${dirname##*/}.py
progwrapper=${dirname##*/}

msg "Create initial python program ${progname}...."
mkpy $progname


msg "Create wrapper script ${progwrapper}..."

/bin/cat >$progwrapper <<EOF
#!/bin/bash -eu

MYDIR=\${0%/*}
[ "\$MYDIR" = . ] && MYDIR=\$PWD

PROGNAME=\${0##*/}.py
cd \$MYDIR

pipenv run ./\${PROGNAME} "\$@"
EOF

chmod +x $progwrapper


msg "Done!"
