#!/bin/bash -eu

# ****************************************************************************
# DESCRIPTION
#   Staffold a simple python3 program incl. argparse and logging
#
# bugs and hints: lrsklemstein@gmail.com
# ****************************************************************************


# ----------------------------------------------------------------------------
# constants
# ----------------------------------------------------------------------------

readonly PROG=${0##*/}

readonly VERSION=1.4

SHORT_USAGE="$PROG [-h] [options] PYPROG" 
readonly SHORT_USAGE

readonly ENTRY_COMMENT="
    #
    # this is the entry point for what your program actually does...
    #
"

# ----------------------------------------------------------------------------
# defaults
# ----------------------------------------------------------------------------
#
shebang='#!/usr/bin/env python3'

dict_str_any='Dict[str, Any]'

log_ini=n
edit=n
force_mode=n
shell_integration=n
is_project_dir=n
role=example

description="WHat's the blue light for?

It light's blue..."

setup_getter='setup = get_prog_setup_or_exit_with_usage()'

rc_ok=0
rc_usage=2
rc_exception=3


# ----------------------------------------------------------------------------
# functions
# ----------------------------------------------------------------------------

print_short_usage_and_exit() {
    echo "Usage: $SHORT_USAGE" >&2
    exit 2
}

print_version_and_exit() {
    echo "This is $PROG version $VERSION" >&2
    exit 2
}

print_long_usage_and_exit() {
/bin/cat >&2 << EOF
mkpy = make python program

A simple tool to create a new python3 program in a unique way.
Functions are used with type hints. The two python functions you should
start with are:

- get_prog_setup_or_exit_with_usage():
    Here you define your program usage and the description using the
    argparse module.

- run():
    This is the actual entry point for your application specific code
    (not main, which is just used as an exception safe start point)

base usage:

$SHORT_USAGE

options:

    -h:
        show this help

    -v:
        show $PROG version

    -e:
        edit file after creation with standard editor

    -f: 
        force mode (overwrite files and directories if required)

    -d:
        set program description (for usage)

    -s:
        shell integration mode: when finished print project path to 
        be able to create a alias like "cd \$(mkpy -s -p xxx)".
        Only applyable with -p option.

    -p:
        interprete PYPROG as project directoy to create incl. git init

    -r ROLE:
        set program role, availble:
            - example : default
            - inout   : expect an input, write an output file
            - nagios  : create Nagios/Icinga style check script

    -L:
        create logging ini file

bugs and hints: lrsklemstein@gmail.com
EOF

exit 2
}

msg() {
    echo "[$PROG] $*" >&2
}

abort() {
    msg "$*"
    exit 1
}

ap_fix_args_example() {
/bin/cat << EOF
    parser.add_argument(
        'FIX_ARG_EXAMPLE', help='FIX_ARG is for, well: please say it',
    )
EOF
}

ap_fix_args_inout() {
/bin/cat << EOF
    parser.add_argument(
        'infile', metavar='INFILE', type=str, help='input file',
    )

    parser.add_argument(
EOF
}

get_run_func() {
    dict_str_any=${1:-$default_dict_str_any}

/bin/cat <<EOF
def run(setup: ${dict_str_any}) -> int:
    logger = logging.getLogger(__name__)
${ENTRY_COMMENT}
    logger.info('Done something...')

    return ${rc_ok}
EOF
}

setup_getter_nagios() {
/bin/cat <<EOF
    try:
        setup = get_prog_setup_or_exit_with_usage()
    except:
        sys.exit(2)
EOF
}

# ----------------------------------------------------------------------------
# main
# ----------------------------------------------------------------------------

while getopts efnvd:r:spLh opt
do
    case $opt in
        h)
            print_long_usage_and_exit ;;
        v)
            print_version_and_exit ;;
        e)
            edit=y ;;
        f) 
            force_mode=y ;;
        d)
            description=$OPTARG ;;
        r)
            role=$OPTARG ;;
        s)
            shell_integration=y
            ;;
        p)
            is_project_dir=y
            ;;
        L)
           log_ini=y ;;
        *)
            print_short_usage_and_exit ;;
    esac
done

case $role in
    example)
        fix_args=$(ap_fix_args_example) ;;
    inout|in_out|input_output)
        fix_args=$(ap_fix_args_inout) ;;
    nagios*|icinga*)
        fix_args=$(ap_fix_args_inout) ;;
    *)
        msg "specified role \"$role\" not implemented"
        exit 2
esac

shift $((OPTIND-1))

[ $# -eq 1 ] || print_short_usage_and_exit

if [ "$shell_integration" = "y" -a "$is_project_dir" = "y" ]
then
    abort "You can not use -s with -p option."
fi

pyprog="$1"

if [ "$pyprog" = "." ]
then
    if [ "$is_project_dir" = "y" ]
    then
        abort "You can not use the dot option together with the -p flag"
    fi

    if [[ $PWD = $HOME || $PWD != *$HOME/* ]]
    then
        echo "Can not autor-create python program here." >&2
        exit 1
    fi
    pyprog=${PWD##*/}
fi

if [ "$is_project_dir" = "y" ]
then
    pydir="${pyprog%.py}"
    if [ -d "$pydir" ]
    then
        if [ "$force_mode" = "y" ]
        then
            /bin/rm -rf "$pydir"
            msg "!!! Deleted existing dir \"$pydir\" due force mode"
        else
            abort "Project dir \"$pydir\" already exist."
        fi
    fi

    mkdir -p "$pydir"

    pyprog="$pydir/${pyprog##*/}".py
fi

pyprog_basename=${pyprog#*.py}

if [ -f "$pyprog" -a "$force_mode" = n ]
then
    abort "\"$pyprog\" already exist"
fi

email=$(git config --global user.email 2>/dev/null) || true
[ -n "$email" ] || email="<unknown>"


run_func=$(get_run_func "$dict_str_any")

/bin/cat >$pyprog <<EOF
${shebang}

"""
${description}
"""

# bugs and hints: ${email}

import argparse
import logging
import logging.config
import sys

from typing import Any, Dict  # , List, Tuple, Callable

__LOG_LEVEL_DEFAULT = logging.INFO


def main() -> None:
    ${setup_getter}

    init_logging(setup)
    logger = logging.getLogger(__name__)

    try:
        sys.exit(run(setup))
    except Exception:
        logger.critical("Abort, rc=${rc_exception}", exc_info=True)
        sys.exit(${rc_exception})


def get_prog_setup_or_exit_with_usage() -> ${dict_str_any}:
    parser = argparse.ArgumentParser(
                description=get_prog_doc(),
                formatter_class=argparse.RawTextHelpFormatter,
            )

    log_group = parser.add_mutually_exclusive_group()

${fix_args}

#   parser.add_argument(
#        '--optional_arg', help='an example for an optional arg',
#   )

    log_group.add_argument(
        '--debug', action='store_true',
        help='enable debug log level',
    )

    log_group.add_argument(
        '--log_cfg', dest='log_cfg',
        help='optional logging cfg in ini format',
    )

    args = vars(parser.parse_args())
    args = {k: '' if v is None else v for k, v in args.items()}

    return args


def get_prog_doc() -> str:
    doc_str = sys.modules['__main__'].__doc__

    if doc_str is not None:
        return doc_str.strip()
    else:
        return '<???>'


def init_logging(setup: $dict_str_any) -> None:
    """Creates either a logger by cfg file or a default instance
    with given log level by arg --log_level (otherwise irgnored)

    """
    if setup['log_cfg'] == '':
        if setup['debug']:
            level = logging.DEBUG
            format = '%(levelname)s - %(message)s'
        else:
            level = __LOG_LEVEL_DEFAULT
            format = '%(message)s'

        logging.basicConfig(level=level, format=format)
    else:
        logging.config.fileConfig(setup['log_cfg'])


${run_func}


if __name__ == '__main__':
    main()
EOF

chmod +x $pyprog

msg "Created \"$pyprog\""

if [ "$is_project_dir" = "y" ]
then
    (
        cd "$pydir"
        echo __pycache__ >> .gitignore

        {
            git init
            git add .
            git commit -m "initial version"
        } >&2

        msg "Initialized git"
    )
fi

if [ "$log_ini" = y ]
then

log_ini_file="${pyprog_basename}_log.ini"
log_output_file="/var/log/${pyprog_basename}.log"

sed "s!%log_output_file%!$log_output_file!g" >$log_ini_file <<EOF
[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=consoleFormatter,logfileFormatter

[logger_root]
level=DEBUG
handlers=fileHandler,consoleHandler

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=consoleFormatter
args=(sys.stderr,)

[handler_fileHandler]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=logfileFormatter
args=('%log_output_file%','midnight',1,30)

[formatter_consoleFormatter]
format=%(levelname)s - %(message)s
datefmt=

[formatter_logfileFormatter]
format=%(asctime)s - %(levelname)s - line %(lineno)s in %(funcName)s(), PID %(process)s - %(message)s
datefmt=
EOF

msg "Created $log_ini_file"
msg "(currently creating log files as $log_output_file, please adjust!)"

fi

if [ $edit = y ]
then
    editor=${EDITOR:-vi}

    if egrep -q "$editor" <<< '^(n?vi|n?vim)$'
    then
        p="logger\.info.*'Done something"
        typeset -i run_pos=$(grep -n "$p" $pyprog  | cut -d: -f1)
        run_pos=run_pos-1
        $editor +$run_pos $pyprog
    else
        $editor $pyprog
    fi
fi

if [ "$shell_integration" = "y" ]
then
    echo "$(readlink -f $pydir)"
fi
