#!/bin/bash -eu

# super stupid "create a dummy execise/experimanteal" python program,
# meant for beeing edited, executed and beeing deleted after short time.

# PLEASE DO NOT USE this for anything else (there's mkpy for...')

# bugs and hints: lrsklemstein@gmail.com


readonly PROG=${0##*/}

if [ $# -ne 1 ]
then
/bin/cat >&2 <<EOF

Create a throw away python program. Not meant for production use!
Will create a minimal python program and edit it right away.

usage: $PROG {pyprog|.}

EOF
exit 2
fi

pyprog="$1"

if [ "$pyprog" = "." ]
then
    if [[ $PWD = $HOME || $PWD != *$HOME/* ]]
    then
        echo "Can not auto-create python program here!" >&2
        exit 1
    fi
    pyprog=${PWD##*/}
fi

cat > $pyprog <<EOF
#!/usr/bin/env python3

# Some throw away code

import sys


def main() -> None:
    sys.exit(0)


if __name__ == '__main__':
    main()
EOF

chmod +x $pyprog

entry_line_num=8

if [ -n "$EDITOR" ]
then
    if  [[ "$EDITOR" == vi? || $EDITOR == nvi? ]]
    then
        ${EDITOR} +$entry_line_num $pyprog
    else
        ${EDITOR} $pyprog
    fi
else
    vi +$entry_line_num $pyprog
fi
