#!/bin/bash -e

# ****************************************************************************
# DESCRIPTION
#   xre == Xresouces (file) editor
#
#   sudo like mechanism to easily edit and activate X environment
# ****************************************************************************

# bugs and hints: lrsklemstein@gmail.com


_VERSION=0.1


shopt -s expand_aliases
alias const='typeset -r'

const XRESOURCES_FILE=$HOME/.Xresources
const EDITOR=${EDITOR:-vi}
const XRDB_PROG=xrdb


msg() { echo "$*" >&2; }

abort() { msg "$*"; exit 1; }

filehash() { sha1sum "$1" | awk '{print $1}'; }


tempfile=$(mktemp)
trap '/bin/rm -f $tempfile' 0 1 2

/bin/cp $XRESOURCES_FILE $tempfile
$EDITOR $tempfile
editor_rc=$?

[ $editor_rc -eq 0 ] || abort "$EDITOR call returned $editor_rc"

[ $(filehash $XRESOURCES_FILE) = $(filehash $tempfile) ] && exit 0

$XRDB_PROG -merge $tempfile
xrdb_rc=$?

[ $xrdb_rc -eq 0 ] || abort "xrdb merge attempt returned $xrdb_rc"

mv $XRESOURCES_FILE ${XRESOURCES_FILE}.old
mv $tempfile $XRESOURCES_FILE
